services:
  db:
    image: mysql:8.0
    container_name: totesbook_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: totesbook
      MYSQL_USER: totesuser
      MYSQL_PASSWORD: totespass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot --silent"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s

  app:
    build: .
    container_name: totesbook_app
    ports:
      - "8080:8080"
      - "4848:4848"
    depends_on:
      db:
        condition: service_healthy
    environment:
      JAVA_OPTS: "-Xmx512m"
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: totesbook
      DB_USER: totesuser
      DB_PASS: totespass
    volumes:
      # El .war es copia automàticament quan Maven el genera
      - ./target/TotEsBook-1.0-SNAPSHOT.war:/opt/glassfish7/glassfish/domains/domain1/autodeploy/TotEsBook.war
      # Mapegem directament el codi font JSP per veure canvis en calent
      # Si canviem JSP, CSS o JS, es veurà en recarregar la pàgina
      - ./src/main/webapp:/opt/glassfish7/glassfish/domains/domain1/applications/TotEsBook/
  # eina gràfica per gestionar la base de dades MySQL.
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  mysql_data:
